name: snowflake
description: Twitter's Snowflake algorithm implementation in Dart.
version: 1.0.0
repository: https://github.com/hawkkiller/snowflake

environment:
  sdk: ^3.0.0

dev_dependencies:
  sizzle_lints: ^1.0.10
  test: ^1.21.0
