name: snowflaker
description: Twitter's snowflaker algorithm implementation in Dart.
version: 1.0.0
repository: https://github.com/hawkkiller/snowflaker

environment:
  sdk: ^3.0.0

dev_dependencies:
  sizzle_lints: ^1.0.10
  test: ^1.21.0
